title: Priyank's Website

# Your name to show in the footer
author: Priyank

 
  
  exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  
  plugins:
  - jekyll-paginate
  - jekyll-sitemap
